import type { Metadata } from "next";
import "./globals.css";
import { mainFont } from "./lib/fonts";
import Navbar from "./lib/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en" // TODO: change here
      className={`${mainFont.className} h-full antialiased`}
    >
      <body className="min-h-full flex">
        <Navbar curPage="home" />
        {children}
      </body>
    </html>
  );
}
